name: Build Web App Demo

on:
  push:
    branches: main
    paths: 'app-services/asp-net-core/**'      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2
    
      - name: Build
        run: |
          cd active-directory-aspnetcore-webapp-openidconnect-v2/5-WebApp-AuthZ/5-2-Groups
          dotnet build --configuration Release /property:GenerateFullPaths=true
          cd bin/Release/netcoreapp3.1
          zip -r app.zip *
          
      - name: Create Release
        # You may pin to the exact commit or the version.
        # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
        uses: ncipollo/release-action@v1.7.3
        with:
          # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
          artifact: active-directory-aspnetcore-webapp-openidconnect-v2/5-WebApp-AuthZ/5-2-Groups/bin/Release/netcoreapp3.1/app.zip
          # The content type of the artifact. Defaults to raw
          artifactContentType: zip
          # An optional body for the release.
          body: 'Updates to the demo app'
          name: 'Active Directory ASP.NET Core Web App OpenIDConnect v2'
